apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: fuse7cxfrest-pipeline
    build: fuse7cxfrest-pipeline
    name: fuse7cxfrest-pipeline
    template: ocp-pipeline-template
    type: pipeline
  name: fuse7cxfrest-pipeline
  namespace: cicd
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: >-
        https://github.com/seravat/fuse6_to_fuse7
    sourceSecret:
      name: github-secret
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  successfulBuildsHistoryLimit: 5